### ISSUE TITLE
The algorithm will recognize all Met to termination codon as potential ORF.

### ISSUE THREAD

**Issue by atlasbioinfo** [leccese/ORF-finder#1]
First of all, thank you for the work you have done, as one of the few jobs on github that uses JS to complete ORF identification.

This algorithm uses a double loop nested traversal sequence, so it recognizes all Met codons to termination codons as ORF, but is that a problem?
For example, if I input a CDS sequence with 20 Met codons, then 20 ORFs will be generated. Right?
I found that NCBI's ORFfinder had no such problem.
It is recommended that certain termination codons only appear in one ORF, which may avoid similar problems.

**Comment by atlasbioinfo** [comment]
There are also the following bugs:
1. The positive chain to the negative chain only underwent reverse(), without complementary pairing.
2. -2 reading box error
3. Repeat the calculation of reverse and substring

I've fixed it in Folk and it's the same result compared to NCBI's ORFfinder.

P.S., currently does not support incomplete termination codon and other features.

**Comment by isabel-nielson** [comment]
Thank you for your PR and bug catches! Also, I like the demo feature a lot

I will add incomplete termination codons to the todo and close this issue
